### PR TITLE
Standardize the image gallery viewers url schema

### PR DESCRIPTION
**Pull request by egauzens**
# Description

Standardized the image gallery viewers url schema as per: https://www.wrike.com/open.htm?id=1020214927

Added redirects for current url schema to new file schema

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Locally via the following datasets and their associated gallery items:

For Testing Biolucida Viewer - Dataset 317 and 321  (There are not nearly as many gallery items as number of JP2 files present in the dataset. There are only viewers available for those datasets which have gallery items)

For Testing Segmentation Viewer - Dataset 295

For Testing Plot Viewer - Dataset 46

For Testing Video Viewer - Dataset 316

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have utilized components from the Design System Library where applicable
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works
- [ ] I updated any relevant QC tests to match my changes found here: https://docs.google.com/document/d/1tlV89PMOv8XlmC7LVqifi7NfQ5-AYN8DuEQpmO7O_2Q

### CODE REVIEW

**Comment by alan-wu** [comment]
@egauzens The new page looks good, viewers are working and the portal successfully redirects the old links but I encounter an issue with the plotvuer at the following route datasets/file/46/2?path=files%2Fderivative%2FExperiment2_Meal-size.csv 
image .

The production page seems to be working https://sparc.science/datasets/plotviewer?dataset_id=46&dataset_version=2&identifier=package%3Acd272e68-94cb-497c-bb17-fbedceadabe8

Can you double check for me if you encounter the same issue, please? Thanks.

**Comment by egauzens** [comment]
> @egauzens The new page looks good, viewers are working and the portal successfully redirects the old links but I encounter an issue with the plotvuer at the following route datasets/file/46/2?path=files%2Fderivative%2FExperiment2_Meal-size.csv image .
> 
> The production page seems to be working https://sparc.science/datasets/plotviewer?dataset_id=46&dataset_version=2&identifier=package%3Acd272e68-94cb-497c-bb17-fbedceadabe8
> 
> Can you double check for me if you encounter the same issue, please? Thanks.

Interesting. It works fine from the gallery, but when navigating to it from the files table, it initially renders correctly, but then turns into that

**Comment by egauzens** [comment]
> @egauzens The new page looks good, viewers are working and the portal successfully redirects the old links but I encounter an issue with the plotvuer at the following route datasets/file/46/2?path=files%2Fderivative%2FExperiment2_Meal-size.csv image .
> 
> The production page seems to be working https://sparc.science/datasets/plotviewer?dataset_id=46&dataset_version=2&identifier=package%3Acd272e68-94cb-497c-bb17-fbedceadabe8
> 
> Can you double check for me if you encounter the same issue, please? Thanks.

Ok I think I got it. On initial render the source url could be null still, I added a check and it has fixed it on my end. Can you sync down the latest changes and check.

**Review by SamanthaKraft — APPROVED** [review]
works for me as well

**Comment by alan-wu** [comment]
> > @egauzens The new page looks good, viewers are working and the portal successfully redirects the old links but I encounter an issue with the plotvuer at the following route datasets/file/46/2?path=files%2Fderivative%2FExperiment2_Meal-size.csv image .
> > The production page seems to be working https://sparc.science/datasets/plotviewer?dataset_id=46&dataset_version=2&identifier=package%3Acd272e68-94cb-497c-bb17-fbedceadabe8
> > Can you double check for me if you encounter the same issue, please? Thanks.
> 
> Ok I think I got it. On initial render the source url could be null still, I added a check and it has fixed it on my end. Can you sync down the latest changes and check.

Thanks, it is working now. It looks good.

**Pull request merged**
