### PR TITLE
Scaffoldstate

### PR DESCRIPTION
**Pull request by alan-wu**
# Description

Add UI and method to save and restore state of the scaffold using data stored in the database. See the API implementation here - https://github.com/nih-sparc/sparc-api/pull/46

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

The following link should restored the scaffold to a specific viewport
https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=105%2F2%2Ffiles%2Fderivative%2FScaffold%2FratStomach_metadata.json&id=ea8add74
New link will also be copied when the share link button is pressed at the top right corner of the scaffold viewer.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by alan-wu** [comment]
@Tehsurfer Can you review this one please?

**Review by Tehsurfer — APPROVED** [review]
Looks good to me! 

Only thing I found is that the share link button seems to be pushing everything else down, but I haven't looked into a way of fixing it:

image

Don't think it's a big deal

**Comment by alan-wu** [comment]
> 
> 
> Looks good to me!
> 
> Only thing I found is that the share link button seems to be pushing everything else down, but I haven't looked into a way of fixing it:
> 
> image
> 
> Don't think it's a big deal

Yes, the button is a component of the page not part of the scaffoldvuer.

**Review by nickerso — APPROVED** [review]
reviewed by @Tehsurfer

**Pull request merged**
