### PR TITLE
feat(Homepage): View more functionality for featured data

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description

The purpose of this PR is to add a "view more" functionality to for featured data on the homepage. This will show six items until the user clicks on the "View more" button.

localhost_3000_(Laptop with HiDPI screen) (12)
localhost_3000_(Laptop with HiDPI screen) (13)

localhost_3000_(iPad) (3)
localhost_3000_(iPad) (4)

localhost_3000_(iPhone X) (4)
localhost_3000_(iPhone X) (5)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Unit tests were created for the following situations:
- Should only show 6 items and a View more button
- Should only show 4 items and no View more button
- Should should all 8 items and no View more button

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by cameronbaney** [comment]
@mahamzayed Can you please review this at your earliest convenience?

**Comment by mahamzayed** [comment]
@cameronbaney For some reason I'm not seeing the updates on the branch. I made sure to pull the latest changes.

**Comment by cameronbaney** [comment]
@mahamzayed If you check out, is the branch the same as `master`?

If it's not and you're testing locally, you'll need to make sure that the `featuredData` has more than six items for the "View more" button to show up. Does the test pass locally? 

Does the new tests for `components/FeaturedData/FeaturedData.spec.js` work? If there is no test, something is definitely wrong with the checkout. I'd delete your local branch and check this out again.

**Review by mahamzayed — APPROVED** [review]
I am still having issues seeing the changes on my branch. Since it might have to do with my git settings, I'm approving this as the code looks good and I don't see why this wouldn't work otherwise.

**Pull request merged**
