### PR TITLE
Make event images links

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description

The purpose of this PR is to make event images links.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- Go to the homepage and scroll down to the News and Upcoming Events section
- The images should link to the same link as the title of the item (internal or external, depending on the entry)
- Go to the News and Events page
- The featured event's image should link to the same link as the title of the item
- The two upcoming and two past event's image should link to the same link as the title of the item
- Click on "Show all events" to go to the events landing page
- The images should link to the same link as the title of the item (internal or external, depending on the entry)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mahamzayed** [comment]
When clicking on the link for the second event `Joint North American Neuromodulation Society` I get the following error in the console. The image links just fine:

```
client.js:97 RangeError: Invalid time value
    at format (index.js:371)
    at VueComponent.formatDate (index.js:11)
    at VueComponent.publishedDate (_id.vue:101)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.evaluate (vue.runtime.esm.js:4584)
    at VueComponent.computedGetter [as publishedDate] (vue.runtime.esm.js:4836)
    at Object.get (vue.runtime.esm.js:2072)
    at Proxy.render (_id.vue?1146:28)
    at VueComponent.Vue._render (vue.runtime.esm.js:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js:4055)
    ```

**Review by mahamzayed — APPROVED** [review]

**Review by mahamzayed — CHANGES_REQUESTED** [review]
LGTM and functionality works, save for that error on the homepage.

**Comment by cameronbaney** [comment]
@mahamzayed That error is the news page and unrelated to this change, however I'm going to fix it in this PR

**Comment by cameronbaney** [comment]
Fixed the issue

**Review by mahamzayed — APPROVED** [review]

**Pull request merged**
