### PR TITLE
Dataset viewers update

### PR DESCRIPTION
**Pull request by Tehsurfer**
# Description

**Genome/Timeseries viewer** added as per [13.1.3 Dynamic dataset viewer RNASeq componentticket ](https://www.wrike.com/open.htm?id=546125808)

**Video viewer** added as per [13.1.1 Dynamic dataset viewer video component](https://www.wrike.com/open.htm?id=546125673)

Both of these viewer pages load the files needed from Blackfynn discover, however there is still some hardcoding for finding if a dataset has suitable files. This has been tested in https://github.com/Tehsurfer/mapintegratedvuer/tree/add-plots-to-sidebar and works, just waiting on the ImageGallery to make calls to scicrunch which will be done in Q2 Y4

The site is available for browsing on [mapcore-demo](https://mapcore-demo.org/staging/sparc-app-viewers-update/) and a free [Heroku instance ](https://sparc-science-add-plotvuer.herokuapp.com/)

Follow these links to get to each of the pages directly:

- [Video viewer](https://mapcore-demo.org/staging/sparc-app-viewers-update/datasets/videoviewer?dataset_version=1&dataset_id=54&file_path=54%2F1%2Ffiles%2Fderivative%2Fsam-P21%20BAT%2Fses-B3tub%2FP21-5%20b3tub%20-%20Movie.mp4)
- [RNASeq viewer](https://mapcore-demo.org/staging/sparc-app-viewers-update/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv&plot_type=heatmap)
- [Timeseries viewer](https://mapcore-demo.org/staging/sparc-app-viewers-update/datasets/plotviewer?dataset_version=1&dataset_id=79&file_path=79%2F1%2Ffiles%2Fprimary%2FCAPdata.csv&plot_type=scatter)

image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

By tracking changes overtime on a Heroku instance at:

https://sparc-science-add-plotvuer.herokuapp.com/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv

and on a generated build hosted on aws at:

https://mapcore-demo.org/staging/sparc-app-viewers-update/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv&plot_type=heatmap 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by cameronbaney — COMMENTED** [review]
These are great and add a lot of functionality to the portal. The only issues I found were on mobile where both the RNASeq viewer and Timeseries viewer aren't responsive and are pushing the viewer controls off to the right of the browser. These are fixable in the dependencies like `PlotVuer`. Would you like to merge this to staging now and create a new PR when the fix is out or fix before merging?

mapcore-demo org_staging_sparc-app-viewers-update_datasets_plotviewer_dataset_version=6 dataset_id=29 file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data csv plot_type=heatmap(iPhone X)

mapcore-demo org_staging_sparc-app-viewers-update_datasets_plotviewer_dataset_version=1 dataset_id=79 file_path=79%2F1%2Ffiles%2Fprimary%2FCAPdata csv plot_type=scatter(iPhone X)

**Comment by alan-wu** [comment]
Thanks @cameronbaney , we will take a look into that.

**Comment by Tehsurfer** [comment]
Just updated this for mobile if you could have a look. 

Can check the heroku [here](https://sparc-science-add-plotvuer.herokuapp.com/datasets/plotviewer?dataset_version=6&dataset_id=29&file_path=29%2F6%2Ffiles%2Fderivative%2FHB-ICN-NegDDCT-data.csv)

**Review by cameronbaney — APPROVED** [review]
Very nice. Working on mobile now! @Tehsurfer

**Pull request merged**
