### PR TITLE
Sparc Portal Header #406rda

### PR DESCRIPTION
**Pull request by mahamzayed**
# Description

The purpose of this PR is to add a header to the SPARC portal. Please note the following that are being worked on but should not block you from reviewing this PR:

1. Scrolling and background overlay is still being worked on for the mobile view when a user opens up the mobile navigation for search.
2. I am aware that the search icon is not facing the right direction and some styling with `px` and `rem` are inconsistent. Those are being worked on as well.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

The header navigation and search should be visible across all pages and should render as per the [designs](https://app.abstract.com/projects/e709ca90-5ba9-11e9-9eaa-59df656d954a/branches/bfc80129-c2a7-410f-aec3-67d6d2f2843b/collections/5a4018fb-1413-473c-b70f-cf0b713a4428?collectionLayerId=03953d52-b36d-46c2-94be-d7ecc7df4fe4)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mahamzayed** [comment]
@cameronbaney Not sure why it's saying 70 files were changed. Tried to pull master so I can merge into my branch and it's telling me it's up to date.

**Comment by mahamzayed** [comment]
> @cameronbaney Not sure why it's saying 70 files were changed. Tried to pull master so I can merge into my branch and it's telling me it's up to date.

I think it's because I merged your homepage changes while I was working on my branch. But I don't think it would have lead to 70 files being changed.

**Comment by cameronbaney** [comment]
@mahamzayed Yes, the reason is because these have the other homepage changes in it, and they haven't been merged to `nih-sparc:master` yet. Once those are merged to master, the changes should be up to date.

**Comment by cameronbaney** [comment]
@mahamzayed to confirm, you tested this for all cross browser functionality in our supported browsers and operating systems?

**Comment by mahamzayed** [comment]
> @mahamzayed to confirm, you tested this for all cross browser functionality in our supported browsers and operating systems?

Yes, the header looks and works as expected for all browsers.

**Comment by mahamzayed** [comment]
> > @mahamzayed to confirm, you tested this for all cross browser functionality in our supported browsers and operating systems?
> 
> Yes, the header looks and works as expected for all browsers.



> The code for this looks good, there are just a few items that will need cleared with Annelise as part of a review. I don't think any of these issues should prevent this from being merged, and can be addressed in additional PRs.
> 
> 1. I believe header should be a fixed header, which would also fix the following bugs on mobile. Confirm this with Annelise.
>    localhost_3000_(Pixel 2) (1)
>    localhost_3000_(Pixel 2)
> 2. The search bar is directly against the right side of the browser, but I feel like this is more of an issue with the header not having any container and being fluid width. It was my interpretation that the header and footer would be in the container of the site, and not fluid width. If that is the case, we can address it when we get our grid system in place.
> 3. Tablet styles are making the navigation wrap to a second line. Usually, tablet headers match the mobile header, but this is something I would confirm as well.
> 
> localhost_3000_(iPad)

@cameronbaney Thanks for pointing these out! The first issue is what I addressed in the description above - I confirmed with Annelise that scrolling would be disabled and there would be an overlay that would be behind the navigation and search bar. As for the other two issues, I'll make a note of them and address with Annelise and future PRs.

**Pull request merged**
