### PR TITLE
Prefill contact forms

### PR DESCRIPTION
**Pull request by ignapas**
# Description

tackling https://www.wrike.com/open.htm?id=1161704527

* To prefill the forms, there has been a refactor in the forms, specially the one that takes the user data that's used in all the others.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually. But I am not super familiar with the forms so more testing is welcomed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have utilized components from the Design System Library where applicable
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by egauzens — CHANGES_REQUESTED** [review]
They appear pretty good so far, however I think there may be something wrong with the saveForm method because when I pulled down your changes and tested them I ran into a few issues (which I think are all related and have something to do with the form default values):

1) The 'I am interested in a SPARC service' option of the 'Share Feedback' tab now has selection issues with the checkboxs behavior as shown here
image

2) The 'Share your story' tab has an invalid default value error on the urlList component (which means that when another submission is created, the first url is blank as shown below which should not be allowed)
image

3) The 'Submit Tool' and 'Share News/Events' pages are erroring out and not rendering as shown below 
image

**Review by egauzens — CHANGES_REQUESTED** [review]
Just a couple last things:

1) This no longer automatically populates the form contact info by default with the users info if they are logged in. If you go onto staging, log in, and then navigate to contact us you will see that the contact info is pre-populated with the logged in users name and email

2) The webpage input link is now missing on the submit tool form as shown here circled in red
image

**Comment by ignapas** [comment]
@egauzens The problem with the url input is solved and pushed but how can I test the login in a local run?

**Comment by egauzens** [comment]
> @egauzens The problem with the url input is solved and pushed but how can I test the login in a local run?

You should be able to use the default env vars defined in the nuxt.config file along with:

AWS_USER_POOL_WEB_CLIENT_ID: 703lm5d8odccu21pagcfjkeaea

I believe that is the only env var you should need to set in order to authenticate vs pennsieve.net instead of pennsieve.io. If you don't have an ORCID login yet you will need to create one when prompted during sign-in

**Comment by ignapas** [comment]
ok, it was a bit tricky to have everything working. but I think I got it right this time... let me know if you find something weird. thanks for taking the time for making the reviews @egauzens

**Review by egauzens — CHANGES_REQUESTED** [review]
Looking better! Works as expected except for one small thing. Please update to only save the user data on submission. The other form data should not be saved. When a user submits a form all the other data should be cleared. This is especially confusing as is because in its current implementation the previous form state is saved once a user submits, so if they make edits to a new form and refresh the page then it will re-populate the page with the old form values since they are saved in the session storage. I think we should just not save those values in session storage

**Comment by ignapas** [comment]
> Looking better! Works as expected except for one small thing. Please update to only save the user data on submission. The other form data should not be saved. When a user submits a form all the other data should be cleared. This is especially confusing as is because in its current implementation the previous form state is saved once a user submits, so if they make edits to a new form and refresh the page then it will re-populate the page with the old form values since they are saved in the session storage. I think we should just not save those values in session storage

At the moment nothing gets saved until the form is sent (and passes validation)
Ok so only user data? That is only the info gathered in `UserContactFormItem.vue`?
Another option would be to add a "Clear form" button in case the user wants to start from scratch.
Please confirm how to proceed

**Comment by egauzens** [comment]
> > Looking better! Works as expected except for one small thing. Please update to only save the user data on submission. The other form data should not be saved. When a user submits a form all the other data should be cleared. This is especially confusing as is because in its current implementation the previous form state is saved once a user submits, so if they make edits to a new form and refresh the page then it will re-populate the page with the old form values since they are saved in the session storage. I think we should just not save those values in session storage
> 
> At the moment nothing gets saved until the form is sent (and passes validation) Ok so only user data? That is only the info gathered in `UserContactFormItem.vue`? Another option would be to add a "Clear form" button in case the user wants to start from scratch. Please confirm how to proceed

I think the former will make most sense and be easier to handle. So only save the user contact info, not the rest of the form data. It should be cleared when the form is submitted

**Comment by ignapas** [comment]
> > > Looking better! Works as expected except for one small thing. Please update to only save the user data on submission. The other form data should not be saved. When a user submits a form all the other data should be cleared. This is especially confusing as is because in its current implementation the previous form state is saved once a user submits, so if they make edits to a new form and refresh the page then it will re-populate the page with the old form values since they are saved in the session storage. I think we should just not save those values in session storage
> > 
> > 
> > At the moment nothing gets saved until the form is sent (and passes validation) Ok so only user data? That is only the info gathered in `UserContactFormItem.vue`? Another option would be to add a "Clear form" button in case the user wants to start from scratch. Please confirm how to proceed
> 
> I think the former will make most sense and be easier to handle. So only save the user contact info, not the rest of the form data. It should be cleared when the form is submitted

I have the fix ready but I am now unable to run the front-end in my machine because of the memory leak problem...

**Review by egauzens — APPROVED** [review]
I tested locally and they work good!

**Pull request merged**
