### PR TITLE
Page hero redesign #4m8vtx

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description
The purpose of this PR is to add the redesigns for the page hero. This is _without_ the images and homepage redesign.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Visit the subpages and ensure that the heroes look consistent with the new design.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by cameronbaney** [comment]
@mahamzayed You're correct, this was done before Resources will merged. I will address that here.

**Comment by cameronbaney** [comment]
@mahamzayed I have addressed the Resources hero issue, as well as an issue with the container on the resources page.

localhost_3000_resources_type=sparcPartners(Laptop with HiDPI screen) (1)

**Comment by mahamzayed** [comment]
According to the [designs](https://app.abstract.com/projects/e709ca90-5ba9-11e9-9eaa-59df656d954a/branches/7ff6a970-9a3d-4f46-ae0a-d10925710fc1/commits/5363dcec5338b715a51151bc89be0ad3fb9185eb/files/a878d736-29fb-4fd2-b67e-dbb681e9f1d9/layers/6BB64ED7-AD5C-4390-BA8D-3661D3ECFE78?collectionId=d5de4d2e-adfe-4b72-966a-f7b31da49aed&collectionLayerId=29145f6f-bf97-4540-a2c0-5a13b77d48a4), the content on the `Resources` hero looks like it's beginning from the left end of the page, while your design has it set in the middle. Does this have to do with our grid system not being in alignment with the designs? Just something I noticed, which is why I had adjusted the styles for the hero when initially working on this.

**Comment by cameronbaney** [comment]
@mahamzayed yes that is the container of our site. My interpretation of the functionality of this page's hero matches the designs, and all other pages. I can confirm this with Annelise when it goes to staging, and address as needed.

**Pull request merged**
