### PR TITLE
SPARC Portal QA CU-fpt7aw

### PR DESCRIPTION
**Pull request by mahamzayed**
# Description

The purpose of this PR is to address the following fixes for SPARC Portal QA before the 11/9 release:

1. Fix the `Last Published` date sorting on Organ detail page
2. Fix layout of Run Simulation button on Simulation page (Firefox)
3. Move Tools and Resources header links out of hero on Tools and Resources page

Please note that #1 is not yet complete - see below for followup.

[Clickup Ticket](https://app.clickup.com/t/fpt7aw)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

**Run Simulation Button layout is being pushed to two lines on Firefox browsers**
Navigate to a simulation page in Firefox. The `Run Simulation` button should now only be displayed on one line. This should also remain the same on a chrome browser as well.

**Move Tools and Resources tab links from page hero header**
Navigate to the Tools and Resources page. The tab links should no longer appear in the header and should look similar in style to those on the News and Events page. The functionality should behave the same way.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mahamzayed** [comment]
@cameronbaney If you have a chance, do you think you can help take a look at why the `Last Published` date in the Datasets results on the Organ detail page isn't sorting? I know you addressed the sorting in a previous ticket but I'm not sure what could be causing the issue as the `onSortChange` is passing the right sort directions.

**Comment by cameronbaney** [comment]
@mahamzayed checking it now

**Comment by cameronbaney** [comment]
@mahamzayed It looks like sorting isn't working for all columns on the datasets and projects tabs on an Organ's page. It appears this hasn't worked in a long time (it's not working production) and it's because there is no `@sort-change="handleSortChange"` listener for the component on `/pages/organs/_organId.vue`. Is this something that was reported to be fixed, or should we create a ticket for it now?

**Comment by mahamzayed** [comment]
@cameronbaney This was reported for just the organ details page but I'm not sure if they're made aware of the issue for the rest of the pages. Leo brought this up to me as part of the QA feedback on Friday.

**Comment by cameronbaney** [comment]
Can this be merged? We need to deploy in an hour.

**Review by cameronbaney — APPROVED** [review]

**Pull request merged**
