### PR TITLE
Fix download files and various Pennsieve migration - CU-tn5ka4

### PR DESCRIPTION
**Pull request by cameronbaney**
# Description

The purpose of this PR is to fix view and download files and various Pennsieve migration.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [Go to a dataset](http://localhost:3000/datasets/86?type=dataset)
- Go to the Files tab
- Files should load
- Open the `primary` folder
- Scroll down to `PelotEtAl_2020_JNeurophys_Supplements.pdf` and click on the name
- The PDF should open in a new tab

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mahamzayed** [comment]
I get this error when trying to click on the PDF file:

```
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:84)
createError @ createError.js:16
handleError @ xhr.js:84
Promise.then (async)
openFile @ FilesTable.vue:475
click @ FilesTable.vue?780f:156
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
```

I made sure to pull the latest changes.

**Review by mahamzayed — CHANGES_REQUESTED** [review]
Code looks good, just that one error. Not sure if there's something in my `nuxt.config.js` that I need to adjust.

**Comment by cameronbaney** [comment]
@mahamzayed I cannot reproduce this. I don't think that there is anything you need to do on Nuxt. Perhaps we can deploy this to staging and see if the error happens there as well?

**Comment by mahamzayed** [comment]
That sounds good to me!

**Review by mahamzayed — APPROVED** [review]
Approving based on our discussion that we'll check this error on dev to see if it's reproducable.

**Pull request merged**
