### PR TITLE
Add sort option for the last published version

### PR DESCRIPTION
**Pull request by Tehsurfer**
# Description
Add sort option for the last published version
image

This was requested here:
https://www.wrike.com/open.htm?id=1234314112

Preview site is here:
https://jesse-sprint-preview.herokuapp.com/data?type=dataset

New replica indeces have been added: 

```
k-core_dev_version_published_time_desc
k-core_dev_version_published_time_asc
SPARC_pr_version_published_time_desc
SPARC_pr_version_published_time_asc
```

**NOTE** I noticed all the default index variables are set to `k-core_dev`. If the variables aren't changed on heroku this is what will be used.

I might make an accompanying pr to change these envVars to default on the production envVars 

## Type of change

Delete those that don't apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Tested locally, and can be viewed on:
https://jesse-sprint-preview.herokuapp.com/data?type=dataset

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have utilized components from the Design System Library where applicable
- [x] I have added or updated unit tests that prove my fix is effective or that my feature works
- [ ] I updated any relevant QC tests to match my changes found here: https://docs.google.com/document/d/1tlV89PMOv8XlmC7LVqifi7NfQ5-AYN8DuEQpmO7O_2Q

### CODE REVIEW

**Comment by Tehsurfer** [comment]
The tests are failing due to incorrect node version, if you wish to test it, try it out manually here:

https://jesse-sprint-preview.herokuapp.com/data?type=dataset

**Comment by Tehsurfer** [comment]
The two failed tests were from `Error: ESOCKETTIMEDOUT` when calling `cy.visit()` 

It's highly likely these are from the test server being overloaded, and not due to the code changes

**Review by alan-wu — COMMENTED** [review]
Are ALGOLIA_INDEX_PUBLISHED_TIME_DESC and ALGOLIA_INDEX_PUBLISHED_TIME_DESC used anywhere else? Remove them from nuxt.config.js if not please.

**Review by alan-wu — APPROVED** [review]
Looks good to me, the failed test is unrelated to this change.

**Pull request merged**
